### ISSUE TITLE
Displaying double amount of stars

### ISSUE THREAD

**Issue by JaySunSyn** [mammooc/flexible-rating#9]
Thanks for the element!

Below displays max=5 stars:
![image](https://cloud.githubusercontent.com/assets/5872432/18708804/f93aed10-7ffc-11e6-9d8c-fd406eef1c98.png)

![image](https://cloud.githubusercontent.com/assets/5872432/18708884/6c0606b8-7ffd-11e6-8649-7fc30b6fc9e6.png)

Polymer versions: 1.6.1 & 1.5.0

Let me know if you need more infos.

**Comment by MrSerth** [comment]
Hi @JaySunSyn,

thanks for your issue. I just took the time to update our dependencies and released a new version. In my tests, this fixed the issue. Let me know, if you still have the same issue.
